import { z } from 'zod'

export const benchSchema = z.object({
  title: z.string().min(2, 'Mindestens 2 Zeichen').max(120),
  description: z.string().max(2000).optional(),
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  category: z.enum(['standard', 'panorama', 'waterfront', 'forest', 'urban', 'picnic']),
  seats: z.number().int().min(1).max(20).optional(),
  material: z.enum(['wood', 'metal', 'stone', 'concrete', 'plastic', 'mixed']).optional(),
  has_roof: z.boolean(),
  has_backrest: z.boolean(),
  has_table: z.boolean(),
  wheelchair_accessible: z.boolean(),
  stroller_friendly: z.boolean(),
  has_bike_rack: z.boolean(),
  has_water_fountain: z.boolean(),
  has_trash_bin: z.boolean(),
  has_bbq: z.boolean(),
  has_playground: z.boolean(),
  dog_friendly: z.boolean(),
  shade: z.boolean(),
  sun: z.boolean(),
  view_lake: z.boolean(),
  view_river: z.boolean(),
  view_mountain: z.boolean(),
  view_city: z.boolean(),
  is_forest: z.boolean(),
  is_park: z.boolean(),
  is_quiet: z.boolean(),
  is_romantic: z.boolean(),
  picnic_friendly: z.boolean(),
  workspace_friendly: z.boolean(),
  notes: z.string().max(1000).optional(),
})

export type BenchFormValues = z.infer<typeof benchSchema>

export const benchFormDefaults: BenchFormValues = {
  title: '',
  description: '',
  lat: 0,
  lng: 0,
  category: 'standard',
  has_roof: false,
  has_backrest: true,
  has_table: false,
  wheelchair_accessible: false,
  stroller_friendly: false,
  has_bike_rack: false,
  has_water_fountain: false,
  has_trash_bin: false,
  has_bbq: false,
  has_playground: false,
  dog_friendly: false,
  shade: false,
  sun: false,
  view_lake: false,
  view_river: false,
  view_mountain: false,
  view_city: false,
  is_forest: false,
  is_park: false,
  is_quiet: false,
  is_romantic: false,
  picnic_friendly: false,
  workspace_friendly: false,
  notes: '',
}
