name: CI
<<<<<<< HEAD
on:
  push:
  pull_request:
jobs:
  verify:
=======

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-build:
>>>>>>> 4ee86bc252e376d71094589ef2683c021bac92a7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build
